branch-defaults:
  main:
    environment: inventory-system-env
    group_suffix: null
  master:
    environment: inventory-system-env
environment-defaults:
  inventory-system-env:
    branch: null
    repository: null
global:
  application_name: inventory-system
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: 4.0.1
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
